# Generated by Django 6.0.1 on 2026-02-22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        # ExpenseSettings
        migrations.CreateModel(
            name='ExpenseSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('require_approval', models.BooleanField(default=False, help_text='Require approval for expenses before they can be marked as paid.', verbose_name='Require Approval')),
                ('approval_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expenses above this amount require approval. 0 means all expenses.', max_digits=10, verbose_name='Approval Threshold')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), help_text='Default tax rate for new expenses.', max_digits=5, verbose_name='Default Tax Rate')),
                ('default_currency', models.CharField(default='EUR', help_text='Default currency for expenses.', max_length=3, verbose_name='Default Currency')),
                ('auto_numbering', models.BooleanField(default=True, help_text='Automatically generate expense numbers.', verbose_name='Auto Numbering')),
                ('number_prefix', models.CharField(default='EXP', help_text='Prefix for auto-generated expense numbers.', max_length=10, verbose_name='Number Prefix')),
            ],
            options={
                'verbose_name': 'Expense Settings',
                'verbose_name_plural': 'Expense Settings',
                'db_table': 'expenses_settings',
                'abstract': False,
                'unique_together': {('hub_id',)},
            },
        ),
        # ExpenseCategory
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('icon', models.CharField(default='folder-outline', help_text='Icon name for the category.', max_length=50, verbose_name='Icon')),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code for the category.', max_length=7, verbose_name='Color')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='expenses.expensecategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'db_table': 'expenses_category',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        # Supplier
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('contact_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Contact Name')),
                ('email', models.EmailField(blank=True, default='', verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Phone')),
                ('tax_id', models.CharField(blank=True, default='', help_text='NIF/CIF of the supplier.', max_length=20, verbose_name='Tax ID')),
                ('address', models.TextField(blank=True, default='', verbose_name='Address')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='City')),
                ('postal_code', models.CharField(blank=True, default='', max_length=10, verbose_name='Postal Code')),
                ('country', models.CharField(default='España', max_length=100, verbose_name='Country')),
                ('website', models.URLField(blank=True, default='', verbose_name='Website')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount spent with this supplier.', max_digits=12, verbose_name='Total Spent')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='Last Purchase Date')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'expenses_supplier',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        # Expense
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('expense_number', models.CharField(db_index=True, max_length=50, verbose_name='Expense Number')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (Net)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='Tax Rate %')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tax Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Amount')),
                ('expense_date', models.DateField(verbose_name='Expense Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='draft', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(blank=True, default='', max_length=50, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, default='', help_text='Invoice/receipt number from supplier.', max_length=100, verbose_name='Reference Number')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expenses/receipts/', verbose_name='Receipt Image')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to='accounts.localuser', verbose_name='Approved By')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.expensecategory', verbose_name='Category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses_expense',
                'ordering': ['-expense_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['hub_id', 'status', '-expense_date'], name='expenses_ex_hub_id__8a3b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['hub_id', 'category', '-expense_date'], name='expenses_ex_hub_id__d4e5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['hub_id', 'supplier'], name='expenses_ex_hub_id__a1b2c3_idx'),
        ),
        # RecurringExpense
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='Tax Rate %')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20, verbose_name='Frequency')),
                ('next_due_date', models.DateField(verbose_name='Next Due Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('auto_create', models.BooleanField(default=False, help_text='Automatically create expense when due date arrives.', verbose_name='Auto Create')),
                ('last_generated_date', models.DateField(blank=True, null=True, verbose_name='Last Generated Date')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to='expenses.expensecategory', verbose_name='Category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to='expenses.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Recurring Expense',
                'verbose_name_plural': 'Recurring Expenses',
                'db_table': 'expenses_recurring',
                'ordering': ['next_due_date'],
                'abstract': False,
            },
        ),
    ]
