# Generated by Django 6.0.1 on 2026-02-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_hub_id_0c4dfb_idx',
            old_name='expenses_ex_hub_id__8a3b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_hub_id_dc43dc_idx',
            old_name='expenses_ex_hub_id__d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_hub_id_4b1fba_idx',
            old_name='expenses_ex_hub_id__a1b2c3_idx',
        ),
    ]
